services:
  lens:
    image: thewh1teagle/lens
    restart: unless-stopped
    command: /lens examples/simple.json
    volumes:
      - ./examples:/examples
    ports:
      - 0.0.0.0:8080:8080
    environment:
      - LENS_HOST=0.0.0.0
      - LENS_PORT=8080